"""
Django settings for Dodong OS.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

from config import __version__ as DODONG_VERSION

# ==========================================================
# Paths
# ==========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES_DIR = BASE_DIR / "templates"
STATIC_DIR = BASE_DIR / "static"
MEDIA_DIR = BASE_DIR / "media"

# ==========================================================
# Environment Variables
# ==========================================================

env = environ.Env()

# Local development loads a .env file for convenience. Production
# (and CI) supply configuration through real environment variables;
# set DJANGO_SKIP_DOTENV=1 to disable the file entirely.
if not env.bool("DJANGO_SKIP_DOTENV", default=False):
    environ.Env.read_env(BASE_DIR / ".env")

# ``DJANGO_ENV`` selects the deployment profile. Anything other than
# "production" is treated as development: security toggles default
# off and SQLite is allowed. "production" flips secure defaults on
# and refuses unsafe fallbacks.
DJANGO_ENV = env("DJANGO_ENV", default="development").strip().lower()
IS_PRODUCTION = DJANGO_ENV == "production"

# ==========================================================
# Security
# ==========================================================

_INSECURE_DEV_SECRET_KEY = "dev-insecure-secret-key-do-not-use-in-production"

SECRET_KEY = env("SECRET_KEY", default=None) or _INSECURE_DEV_SECRET_KEY

DEBUG = env.bool("DEBUG", default=False)

if IS_PRODUCTION:
    if SECRET_KEY == _INSECURE_DEV_SECRET_KEY:
        raise ImproperlyConfigured(
            "SECRET_KEY must be set in production (DJANGO_ENV=production)."
        )
    if DEBUG:
        raise ImproperlyConfigured(
            "DEBUG must be False in production (DJANGO_ENV=production)."
        )

# Hosts / CSRF origins. Empty defaults are fine for local dev over
# 127.0.0.1; production must supply real values.
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

if not ALLOWED_HOSTS and not IS_PRODUCTION:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]", "testserver"]

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# Login-required views redirect here (the built-in admin login is
# the only login form Dodong OS ships in v1.0).
LOGIN_URL = env("LOGIN_URL", default="/admin/login/")

if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS must be set in production."
    )

# ==========================================================
# Installed Apps
# ==========================================================

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "django_htmx",
]

LOCAL_APPS = [
    "apps.health",
    "apps.dashboard",
    "apps.companies",
    "apps.leads",
    "apps.scanner",
    "apps.ai",
    "apps.leadfinder",
    "apps.automation",
    "apps.knowledge",
]

INSTALLED_APPS = (
    DJANGO_APPS
    + THIRD_PARTY_APPS
    + LOCAL_APPS
)

# ==========================================================
# Middleware
# ==========================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

# ==========================================================
# Templates
# ==========================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        # Global templates
        "DIRS": [
            TEMPLATES_DIR,
        ],

        # App templates
        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context_processors.version",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ==========================================================
# Database
# ==========================================================
#
# Production: set DATABASE_URL to a PostgreSQL DSN, e.g.
#   postgres://USER:PASSWORD@HOST:5432/NAME
# Development: DATABASE_URL may be omitted to use local SQLite.
# Production (DJANGO_ENV=production) refuses the SQLite fallback so
# a misconfigured deploy fails fast instead of writing to an
# ephemeral file.
#
_DATABASE_URL = env("DATABASE_URL", default="")

if _DATABASE_URL:
    DATABASES = {
        "default": env.db_url_config(_DATABASE_URL),
    }
    DATABASES["default"]["CONN_MAX_AGE"] = env.int(
        "DB_CONN_MAX_AGE",
        default=60,
    )
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True
elif IS_PRODUCTION:
    raise ImproperlyConfigured(
        "DATABASE_URL (PostgreSQL) is required in production; "
        "the SQLite fallback is development-only."
    )
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# ==========================================================
# Password Validation
# ==========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ==========================================================
# Internationalization
# ==========================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# ==========================================================
# Static Files (served in production by WhiteNoise)
# ==========================================================

STATIC_URL = "static/"

STATICFILES_DIRS = [
    STATIC_DIR,
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Production hashes + compresses static assets (needs a
# `collectstatic` build step, which the deploy runbook includes).
# Development / tests use plain storage so no manifest is required.
_STATICFILES_BACKEND = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
    if IS_PRODUCTION
    else "django.contrib.staticfiles.storage.StaticFilesStorage"
)

STORAGES = {
    "default": {
        "BACKEND": (
            "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": _STATICFILES_BACKEND,
    },
}

# In development WhiteNoise serves straight from the static finders
# so no `collectstatic` is needed and no missing-dir warning fires.
if not IS_PRODUCTION:
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True

# ==========================================================
# Media Files
# ==========================================================
#
# Dodong OS has no user-facing uploads today; MEDIA_ROOT is only a
# Django default. If uploads are added later, production must point
# MEDIA_ROOT at durable storage (not the container filesystem).
#

MEDIA_URL = "/media/"

MEDIA_ROOT = MEDIA_DIR

# ==========================================================
# Default Primary Key
# ==========================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==========================================================
# Production Security (Phase 10)
# ==========================================================
#
# Defaults follow DJANGO_ENV: on in production, off in
# development (so local dev keeps working over plain HTTP). Every
# value is still individually env-overridable.
#
# Azure App Service / most PaaS terminate TLS at the edge and
# forward the original scheme in X-Forwarded-Proto.
#

if env.bool("USE_X_FORWARDED_PROTO", default=IS_PRODUCTION):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = env.bool(
    "SECURE_SSL_REDIRECT",
    default=IS_PRODUCTION,
)

SESSION_COOKIE_SECURE = env.bool(
    "SESSION_COOKIE_SECURE",
    default=IS_PRODUCTION,
)

CSRF_COOKIE_SECURE = env.bool(
    "CSRF_COOKIE_SECURE",
    default=IS_PRODUCTION,
)

SECURE_HSTS_SECONDS = env.int(
    "SECURE_HSTS_SECONDS",
    default=31536000 if IS_PRODUCTION else 0,
)

SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=IS_PRODUCTION,
)

SECURE_HSTS_PRELOAD = env.bool(
    "SECURE_HSTS_PRELOAD",
    default=False,
)

SECURE_CONTENT_TYPE_NOSNIFF = True

X_FRAME_OPTIONS = "DENY"

# ==========================================================
# Logging (Phase 10)
# ==========================================================
#
# Console-only (containers log to stdout). Level is env-tunable.
# Formatters never render request bodies, headers, env, or
# credentials.
#

LOG_LEVEL = env("LOG_LEVEL", default="INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": (
                "%(asctime)s %(levelname)s %(name)s %(message)s"
            ),
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "apps": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# ==========================================================
# Background Automation (Phase 6)
# ==========================================================
#
# Thresholds for the deterministic CRM checks run by
# `python manage.py run_crm_checks`. These are product decisions,
# not architectural constants — tune them per deployment via env.
# The roadmap does not yet fix these values; the defaults below are
# conservative starting points and should be reviewed with the
# business.
#
#   CRM_DUE_SOON_HOURS  - a task is "due soon" when its due_date is
#                         in the future but within this many hours.
#   CRM_STALE_LEAD_DAYS - an active lead is "stale" when it has had
#                         no meaningful activity for this many days.
#
# Hardening (Phase 6E2), also env-tunable product decisions:
#
#   CRM_AUTOMATION_STALE_RUN_MINUTES - a ScheduledCheckRun stuck in
#       "running" for longer than this is treated as a crashed
#       process: it is marked failed (STALE_RUN_RECOVERED) so a new
#       run can start. Must be comfortably longer than a healthy run.
#   CRM_AUTOMATION_AI_TIMEOUT_SECONDS - bounded network timeout for
#       the optional AI digest summary during automation only. A
#       timeout degrades to the deterministic fallback; it never
#       fails the run. Interactive AI usage is unaffected.
#

CRM_DUE_SOON_HOURS = env.int(
    "CRM_DUE_SOON_HOURS",
    default=48,
)

CRM_STALE_LEAD_DAYS = env.int(
    "CRM_STALE_LEAD_DAYS",
    default=14,
)

CRM_AUTOMATION_STALE_RUN_MINUTES = env.int(
    "CRM_AUTOMATION_STALE_RUN_MINUTES",
    default=30,
)

CRM_AUTOMATION_AI_TIMEOUT_SECONDS = env.int(
    "CRM_AUTOMATION_AI_TIMEOUT_SECONDS",
    default=15,
)

# ==========================================================
# RAG / AI Memory (Phase 7)
# ==========================================================
#
# Deterministic knowledge retrieval (SQLite deployment has no
# pgvector, so retrieval is lexical, not embedding-based). All
# env-tunable:
#
#   RAG_CHUNK_SIZE          - max characters per knowledge chunk.
#   RAG_CHUNK_OVERLAP       - characters of trailing context shared
#                             between consecutive chunks.
#   RAG_RETRIEVAL_LIMIT     - default number of evidence chunks
#                             returned by a knowledge search.
#   RAG_AI_TIMEOUT_SECONDS  - bounded provider network timeout for
#                             the grounded RAG answer only (own
#                             setting, not shared with automation).
#                             A timeout degrades to a deterministic
#                             evidence-only answer; RAG also uses
#                             max_retries=0.
#

RAG_CHUNK_SIZE = env.int(
    "RAG_CHUNK_SIZE",
    default=800,
)

RAG_CHUNK_OVERLAP = env.int(
    "RAG_CHUNK_OVERLAP",
    default=120,
)

RAG_RETRIEVAL_LIMIT = env.int(
    "RAG_RETRIEVAL_LIMIT",
    default=5,
)

RAG_AI_TIMEOUT_SECONDS = env.int(
    "RAG_AI_TIMEOUT_SECONDS",
    default=15,
)

# ==========================================================
# Input limits (Phase 10 production hardening)
# ==========================================================
#
# Bounded, centralized, generous. Enforced at the service /
# proposal / tool boundary with a structured error - never a
# silent truncation. Existing rows are untouched (no DB migration).
#
#   CRM_NOTE_MAX_LENGTH     - max characters for a controlled lead
#                             note (LeadActivity.description via the
#                             add_lead_note flow). Also caps the
#                             signed proposal token and AIActionAudit
#                             JSON size.
#   RAG_QUERY_MAX_CHARS     - max characters for a knowledge query.
#   KNOWLEDGE_DOC_MAX_CHARS - max characters for one ingested
#                             knowledge document (normalized text).
#

CRM_NOTE_MAX_LENGTH = env.int(
    "CRM_NOTE_MAX_LENGTH",
    default=5000,
)

RAG_QUERY_MAX_CHARS = env.int(
    "RAG_QUERY_MAX_CHARS",
    default=2000,
)

KNOWLEDGE_DOC_MAX_CHARS = env.int(
    "KNOWLEDGE_DOC_MAX_CHARS",
    default=200000,
)

# ==========================================================
# Lead Scanner (Phase 4)
# ==========================================================
#
# Discovery only - the scanner never creates a CRM Lead without an
# explicit staff import. All values are conservative defaults;
# tune the qualification profile per operator.
#
#   SCANNER_PROFILE            - deterministic qualification profile
#                               (dict; missing keys fall back to
#                               apps/scanner/scoring.DEFAULT_PROFILE).
#   SCANNER_SCORE_HIGH/MEDIUM  - qualification band thresholds.
#   SCANNER_AI_TIMEOUT_SECONDS - bounded timeout for the OPTIONAL,
#                               non-authoritative AI explanation note.
#

SCANNER_PROFILE = {
    "required_skills": env.list(
        "SCANNER_REQUIRED_SKILLS",
        default=["power bi", "sql"],
    ),
    "preferred_skills": env.list(
        "SCANNER_PREFERRED_SKILLS",
        default=["dax", "power query", "tableau", "python"],
    ),
    "role_keywords": env.list(
        "SCANNER_ROLE_KEYWORDS",
        default=["analyst", "bi", "data", "developer", "engineer"],
    ),
    "excluded_terms": env.list(
        "SCANNER_EXCLUDED_TERMS",
        default=["unpaid", "volunteer"],
    ),
    "remote_required": env.bool(
        "SCANNER_REMOTE_REQUIRED",
        default=False,
    ),
    "min_compensation": env.int(
        "SCANNER_MIN_COMPENSATION",
        default=0,
    ),
    "recency_days": env.int(
        "SCANNER_RECENCY_DAYS",
        default=30,
    ),
}

SCANNER_SCORE_HIGH = env.int("SCANNER_SCORE_HIGH", default=80)
SCANNER_SCORE_MEDIUM = env.int("SCANNER_SCORE_MEDIUM", default=60)
SCANNER_AI_TIMEOUT_SECONDS = env.int(
    "SCANNER_AI_TIMEOUT_SECONDS",
    default=15,
)

# Max size of a staff-uploaded lead CSV (bytes). Discovery only -
# an upload never creates a CRM lead.
SCANNER_CSV_MAX_BYTES = env.int(
    "SCANNER_CSV_MAX_BYTES",
    default=2_000_000,
)

# ----------------------------------------------------------
# Job URL scanner (paste-a-link discovery)
# ----------------------------------------------------------
#
# Fetches ONE public job posting page and runs it through the same
# normalize -> dedup -> deterministic score -> review queue pipeline
# as every other source. Never creates a CRM lead.
#
# The fetched page is untrusted input:
#   - only http/https, no redirects to private/loopback/link-local IPs
#   - bounded timeout, bounded response size, bounded redirects
#   - HTML is reduced to text; no scripts are ever executed or rendered
#
SCANNER_URL_FETCH_TIMEOUT = env.float(
    "SCANNER_URL_FETCH_TIMEOUT",
    default=8.0,
)
SCANNER_URL_MAX_BYTES = env.int(
    "SCANNER_URL_MAX_BYTES",
    default=2_500_000,
)
SCANNER_URL_MAX_REDIRECTS = env.int(
    "SCANNER_URL_MAX_REDIRECTS",
    default=3,
)
SCANNER_URL_USER_AGENT = env(
    "SCANNER_URL_USER_AGENT",
    default=(
        "DodongOS-LeadScanner/1.0 "
        "(+https://dodong.local/scanner)"
    ),
)
# Escape hatch for local development only: allow fetching private /
# loopback addresses. MUST stay False in production.
SCANNER_URL_ALLOW_PRIVATE = env.bool(
    "SCANNER_URL_ALLOW_PRIVATE",
    default=False,
)