# Generated by Django 6.0.7 on 2026-08-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.UUIDField(unique=True)),
                ('action', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('executed', 'Executed'), ('failed', 'Failed')], max_length=20)),
                ('lead_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('result_task_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('proposal_data', models.JSONField(default=dict)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
