# Generated by Django 6.0.7 on 2026-09-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['active'], name='knowledge_k_active_ef51cf_idx'),
        ),
    ]
