# Generated by Django 6.0.7 on 2026-08-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ai_last_analyzed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_next_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
