# Generated by Django 6.0.7 on 2026-09-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('due_soon_task', 'Due-soon task'), ('stale_lead', 'Stale lead')], max_length=32)),
                ('lead_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('task_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('finding_data', models.JSONField(default=dict)),
                ('dedup_key', models.CharField(max_length=128, unique=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at', 'id'],
            },
        ),
    ]
