# Generated by Django 6.0.7 on 2026-09-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_crmdigest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledcheckrun',
            options={'ordering': ['-started_at', '-id']},
        ),
        migrations.AddField(
            model_name='scheduledcheckrun',
            name='summary_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scheduledcheckrun',
            name='summary_source',
            field=models.CharField(blank=True, choices=[('ai_provider', 'AI provider'), ('deterministic_fallback', 'Deterministic fallback')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='scheduledcheckrun',
            name='summary_status',
            field=models.CharField(blank=True, choices=[('AI_SUMMARY_OK', 'AI summary OK'), ('AI_SUMMARY_FAILED', 'AI summary failed')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='scheduledcheckrun',
            name='summary_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
