# Generated by Django 6.0.7 on 2026-09-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_alter_scheduledcheckrun_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='crmdigest',
            index=models.Index(fields=['resolved_at'], name='automation__resolve_fcb206_idx'),
        ),
        migrations.AddIndex(
            model_name='crmdigest',
            index=models.Index(fields=['finding_type', 'resolved_at'], name='automation__finding_e26ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledcheckrun',
            index=models.Index(fields=['status'], name='automation__status_98b826_idx'),
        ),
    ]
