# Generated by Django 6.0.7 on 2026-07-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('technologies', models.TextField(blank=True)),
                ('lead_score', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('contacted', 'Contacted'), ('proposal', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
