# Generated by Django 6.0.7 on 2026-08-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='pain_points',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='recommended_services',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='salary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='work_setup',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
