# Generated by Django 6.0.7 on 2026-08-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Lead Created'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('ai_analysis', 'AI Analysis'), ('proposal_sent', 'Proposal Sent'), ('won', 'Lead Won'), ('lost', 'Lead Lost')], default='note', max_length=20),
        ),
    ]
