# Generated by Django 6.0.7 on 2026-09-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_leadtask'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', '-created_at'], name='leads_leada_lead_id_26db76_idx'),
        ),
        migrations.AddIndex(
            model_name='leadtask',
            index=models.Index(fields=['status', 'due_date'], name='leads_leadt_status_d5a7e5_idx'),
        ),
    ]
