# Generated by Django 6.0.7 on 2026-09-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('source_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('source_url', models.URLField(blank=True, default='')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('opportunity_title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('work_arrangement', models.CharField(blank=True, default='', max_length=64)),
                ('compensation_text', models.CharField(blank=True, default='', max_length=255)),
                ('raw_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('dedup_key', models.CharField(max_length=200, unique=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('score_components', models.JSONField(default=dict)),
                ('score_reasons', models.JSONField(default=list)),
                ('qualification', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=8)),
                ('ai_note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('imported', 'Imported')], default='new', max_length=16)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('imported_lead_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score', '-discovered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('candidates_seen', models.PositiveIntegerField(default=0)),
                ('candidates_created', models.PositiveIntegerField(default=0)),
                ('candidates_updated', models.PositiveIntegerField(default=0)),
                ('rows_rejected', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('row_errors', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.AddIndex(
            model_name='leadcandidate',
            index=models.Index(fields=['status'], name='scanner_lea_status_034522_idx'),
        ),
        migrations.AddIndex(
            model_name='leadcandidate',
            index=models.Index(fields=['source'], name='scanner_lea_source_7c9340_idx'),
        ),
        migrations.AddIndex(
            model_name='leadcandidate',
            index=models.Index(fields=['qualification'], name='scanner_lea_qualifi_0f9def_idx'),
        ),
        migrations.AddIndex(
            model_name='leadcandidate',
            index=models.Index(fields=['-score'], name='scanner_lea_score_b528c1_idx'),
        ),
        migrations.AddIndex(
            model_name='leadcandidate',
            index=models.Index(fields=['source', 'source_identifier'], name='scanner_lea_source_5d637b_idx'),
        ),
        migrations.AddIndex(
            model_name='leadscanrun',
            index=models.Index(fields=['source'], name='scanner_lea_source_c3e977_idx'),
        ),
        migrations.AddIndex(
            model_name='leadscanrun',
            index=models.Index(fields=['status'], name='scanner_lea_status_7bc2bf_idx'),
        ),
    ]
