# Generated by Django 6.0.7 on 2026-09-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_leadcandidate_leadscanrun_delete_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcandidate',
            name='skills_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='leadcandidate',
            name='status',
            field=models.CharField(choices=[('discovered', 'Discovered'), ('new', 'New'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('imported', 'Imported')], default='new', max_length=16),
        ),
    ]
